apiVersion: v1
kind: Service
metadata:
  name: jk-service
  labels:
    app: jk-devops-project
spec:
  selector:
    app: jk-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200

